services:
  - type: web
    name: storage-valet
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: REPLIT_APP_ID
        sync: false
      - key: REPLIT_APP_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: EMAIL_API_KEY
        sync: false
